const FETCH_DATA_LOADING = "FETCH_DATA_LOADING"
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"
const FETCH_DATA_ERROR = "FETCH_DATA_ERROR"

const PRODUCT_LOADING = "PRODUCT_LOADING"
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
const PRODUCT_ERROR = "PRODUCT_ERROR"

const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING"
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR"
const CURRENT_PRODUCT_SUCCESS = "CURRENT_PRODUCT_SUCCESS"

export { FETCH_DATA_LOADING, FETCH_DATA_SUCCESS, FETCH_DATA_ERROR, PRODUCT_LOADING, PRODUCT_SUCCESS, PRODUCT_ERROR, CURRENT_PRODUCT_LOADING, CURRENT_PRODUCT_SUCCESS, CURRENT_PRODUCT_ERROR }
